M48
; DRILL file {KiCad 7.0.11+dfsg-1build4} date Sat Sep 26 08:06:03 2026
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-26T08:06:03+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11+dfsg-1build4
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
%
G90
G05
T1
X5.0Y-5.0
X5.0Y-120.0
X105.0Y-5.0
X105.0Y-120.0
M30
